# config.yml
theme: jekyll-theme-slate # (or any theme you may have been using before)
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      custom_css: "/main/styles.css" 
